### ISSUE TITLE
macOS 15 beta 3 performance

### ISSUE THREAD

**Issue by amostamu** [smpanaro/coreml-llm-cli#1]
m3 pro gain a big performance boost on macOS 15
![Screenshot 2024-07-11 at 15 45 14](https://github.com/smpanaro/coreml-llm-cli/assets/41209757/d5ec4afb-5e57-4e1b-934d-9ecc2e5f8620)
![Screenshot 2024-07-11 at 15 45 35](https://github.com/smpanaro/coreml-llm-cli/assets/41209757/af698743-c738-4e1b-b69c-6d503e99f8ea)

**Comment by amostamu** [comment]
ane 7.5w

**Comment by smpanaro** [comment]
@amostamu Wow! Thanks for sharing. That looks like it is on the `main` branch, correct?

Try switching to the `sequoia` branch and running this:
```
swift run -c release LLMCLI --repo-id smpanaro/Llama-2-7b-coreml --repo-directory sequoia --max-new-tokens 80
```
Hopefully it’s even faster. 🤞

**Comment by amostamu** [comment]
Yes it is even faster when using sequoia branch. That is speed of second time
Compile + Load: 0.51 sec
Prompt        : 726.74 sec
                704.52 token / sec
Generate      : 85.41 +/- 2.67 ms / token
                11.72 +/- 0.29 token / sec

**Comment by smpanaro** [comment]
Cool, thanks for trying. I expected/hoped it would be a bit higher but I'll take it.

**Comment by smpanaro** [comment]
Added this to the README. Thanks again for the info!
